### ISSUE TITLE
install

### ISSUE THREAD

**Issue by wpotiant** [j4cksw/git-imc-workshop-01#18]
<p>ก่อนที่จะใช้งานคุณต้องติดตั้ง Git ก่อน โดยคุณสามารถทำได้หลายวิธี วิธีหลักสองวิธีคือติดตั้งจากซอร์สโค้ดหรือติดตั้งจากแพคเกจที่มีอยู่แล้วสำหรับระบบปฏิบัติการของคุณ</p>
        <h3>สำหรับ Windows สามารถ download และติดตั้ง Git ได้จาก GitHub page</h3>
        <pre>download ได้ที่ http://msysgit.github.com/</pre>

**Comment by boemxp** [comment]
Fixed
